# University of Melbourne
# COMP90024 - Team52
# Name of contributors and student id:
# * Edward Formainir: 1073708
# * Niloy Sarkar: 991245
# * Marc Girard: 1155873
# * Runqi Zhu: 793024
---
# setup LXDE desktop environment on all instances
- name: execute LXDE shell script
  script: ./run-LXDE.sh

