# University of Melbourne
# COMP90024 - Team52
# Name of contributors and student id:
# * Edward Formainir: 1073708
# * Niloy Sarkar: 991245
# * Marc Girard: 1155873
# * Runqi Zhu: 793024
---
# install couchDB
- name: Install couchDB
  become: yes
  pip:
    name: ['couchdb']
    state: latest
# pip install couchdb

# install StringColor
- name: Install StringColor
  become: yes
  pip:
    name: ['string-color']
    state: latest

# install cryptography
- name: Install cryptography
  become: yes
  pip:
    name: ['cryptography']
    state: latest
# pip install cryptography

# copy files for data collector
- name: Copy files for data collector
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'steamid.py', dest: '~/' }
    - { src: 'friendid.py', dest: '~/' }
    - { src: 'cityupdater.py', dest: '~/' }
    - { src: 'city.sh', dest: '~/' }
    - { src: 'Aus.json', dest: '~/' }

# run data collector script
- name: execute basic steam id data collector on a first instance
  shell: python3 steamid.py 
  when: inventory_hostname == '172.26.134.6'

# run friend data collector script
- name: execute friend data collector on a second instance
  shell: python3 friendid.py 
  when: inventory_hostname == '172.26.133.171'

# run city shell script to add the proper city names and coordinates
- name: execute city ushell script on a third instance
  shell: ./city.sh
  when: inventory_hostname == '172.26.133.101'


