- hosts: Wordpress
  vars_files:
    - host_vars/wordpress.yaml
  gather_facts: false

  roles:
    - role: common
    - role: volumes
    - role: docker
    - role: wordpress
    - role: LXDE
    - role: couchDB-setup
    - role: data-collector
    