# University of Melbourne
# COMP90024 - Team52
# Name of contributors and student id:
# * Edward Formainir: 1073708
# * Niloy Sarkar: 991245
# * Marc Girard: 1155873
# * Runqi Zhu: 793024

- hosts: Wordpress
  vars_files:
    - host_vars/wordpress.yaml
  gather_facts: false

  roles:
    - role: common
    - role: volumes
    - role: docker
    # - role: wordpress
    - role: LXDE
    - role: couchDB-setup
    - role: data-collector
    